### ISSUE TITLE
マルチログイン機能

### ISSUE THREAD

**Issue by yuitakiguchi** [yuitakiguchi/UberEats#3]
# やること
- [ ] マルチログイン機能
- [ ] shop,user,admin,deliverがログインできるようにする

# 完了の定義
- [ ] shop,user,admin,deliverがログインできるようになったら

###正常系
##ログインできる
 - [ ] shopの登録済のアカウントでログインできること
 - [ ] userの登録済のアカウントでログインできること
 - [ ] adminの登録済のアカウントでログインできること
 - [ ] deliverの登録済のアカウントでログインできること
##登録できる
 - [ ] shopの登録済のアカウントで登録できること
 - [ ] userの登録済のアカウントで登録できること
 - [ ] adminの登録済のアカウントで登録できること
 - [ ] deliverの登録済のアカウントで登録できること
###異常系
##登録されていないアカウント
 - [ ] shopの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
 - [ ] userの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
 - [ ] adminの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
 - [ ] deliverの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
 - [ ] 別の登録されているアカウントと混同されていないか
 - [ ] userに登録されているアカウント情報をshopのログイン画面で入力してログインできずに登録画面にリダイレクトすること

**Comment by SuguruOoki** [comment]
# 検証

## 正常系

### ログインできる

- [ ] shopの登録済のアカウントでログインできること
- [ ] userの登録済のアカウントでログインできること
- [ ] adminの登録済のアカウントでログインできること
- [ ] deliverの登録済のアカウントでログインできること

### 登録できる

- [ ] shopの登録済のアカウントで登録できること
- [ ] userの登録済のアカウントで登録できること
- [ ] adminの登録済のアカウントで登録できること
- [ ] deliverの登録済のアカウントで登録できること


## 異常系

### 登録されていないアカウント

- [ ] shopの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
- [ ] userの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
- [ ] adminの登録されていないアカウントでログインできずに登録画面にリダイレクトすること
- [ ] deliverの登録されていないアカウントでログインできずに登録画面にリダイレクトすること

### 別の登録されているアカウントと混同されていないか

- [ ] userに登録されているアカウント情報をshopのログイン画面で入力してログインできずに登録画面にリダイレクトすること
